version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schooldb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - school-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - school-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - school-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  user-service:
    image: school_platform-user-service:latest
    env_file:
      - ./user-service/.env.docker
    ports:
      - "3000:3000"
    networks:
      - school-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  menu-service:
    image: school_platform-menu-service:latest
    env_file:
      - ./menu-service/.env.docker
    ports:
      - "3001:3001"
    networks:
      - school-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  school-net:
    driver: overlay

volumes:
  mysql_data:
  keycloak_data:
