# build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_KC_URL
ARG VITE_KC_REALM
ARG VITE_KC_CLIENT_ID
ARG VITE_USERS_BASE
ARG VITE_MENUS_BASE
ARG VITE_ORDERS_BASE

ENV VITE_KC_URL=$VITE_KC_URL
ENV VITE_KC_REALM=$VITE_KC_REALM
ENV VITE_KC_CLIENT_ID=$VITE_KC_CLIENT_ID
ENV VITE_USERS_BASE=$VITE_USERS_BASE
ENV VITE_MENUS_BASE=$VITE_MENUS_BASE
ENV VITE_ORDERS_BASE=$VITE_ORDERS_BASE

RUN npm run build

# runtime stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

